from fastapi import APIRouter, HTTPException, Query, status
from pydantic import BaseModel, Field


# -----------------------------
# Router
# -----------------------------

router = APIRouter(
    prefix="/models",
    tags=["Models"]
)


# -----------------------------
# Pydantic Models
# -----------------------------

# Used when returning a model
class Model(BaseModel):
    id: int
    name: str
    provider: str


# Used when creating a model
# ID is generated by the server
class ModelCreate(BaseModel):
    name: str = Field(
        ...,
        min_length=1,
        max_length=100
    )

    provider: str = Field(
        ...,
        min_length=1,
        max_length=100
    )


# -----------------------------
# Dummy In-Memory Database
# -----------------------------

db_models = [
    {
        "id": 1,
        "name": "Llama 3",
        "provider": "Meta"
    },
    {
        "id": 2,
        "name": "GPT-4o",
        "provider": "OpenAI"
    },
]


# -----------------------------
# GET - All Models
# -----------------------------

@router.get(
    "/",
    response_model=list[Model]
)
def get_all_models(
    provider: str = None
):
    if provider:
        return [
            model
            for model in db_models
            if model["provider"].lower() == provider.lower()
        ]

    return db_models


# -----------------------------
# GET - Search Models
# -----------------------------

@router.get(
    "/search",
    response_model=list[Model]
)
def search_models(
    provider: str = None,
    limit: int = Query(
        default=10,
        ge=1,
        le=100
    ),
):
    results = db_models

    if provider:
        results = [
            model
            for model in results
            if provider.lower() in model["provider"].lower()
        ]

    return results[:limit]


# -----------------------------
# GET - Model by ID
# -----------------------------

@router.get(
    "/{model_id}",
    response_model=Model
)
def get_model_by_id(
    model_id: int
):
    for model in db_models:

        if model["id"] == model_id:
            return model

    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail="Model not found"
    )


# -----------------------------
# POST - Create Model
# -----------------------------

@router.post(
    "/",
    response_model=Model,
    status_code=status.HTTP_201_CREATED
)
def create_model(
    model: ModelCreate
):

    new_id = max(
        [model["id"] for model in db_models],
        default=0
    ) + 1

    new_model = {
        "id": new_id,
        "name": model.name,
        "provider": model.provider,
    }

    db_models.append(new_model)

    return new_model


# -----------------------------
# PUT - Update Model
# -----------------------------

@router.put(
    "/{model_id}",
    response_model=Model
)
def update_model(
    model_id: int,
    updated_model: Model
):

    for index, model in enumerate(db_models):

        if model["id"] == model_id:

            db_models[index] = updated_model.model_dump()

            return updated_model

    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail="Model not found"
    )


# -----------------------------
# DELETE - Delete Model
# -----------------------------

@router.delete(
    "/{model_id}",
    response_model=Model
)
def delete_model(
    model_id: int
):

    for index, model in enumerate(db_models):

        if model["id"] == model_id:

            deleted_model = db_models.pop(index)

            return deleted_model

    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail="Model not found"
    )
